---
abstract: 'Calculate Distances and Closest Locations'
author:
  - 'Aran Clary Deltac <bluefeet@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Distance
no_index:
  directory:
    - inc
    - t
recommends:
  Geo::Distance::XS: 0
requires:
  Math::Complex: 0
  perl: 5.8.3
resources:
  homepage: http://github.com/bluefeet/geo-distance/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bluefeet/geo-distance.git
version: 0.16
